name: build-frontend

on:
  push:
    branches: [ "main", "developer" ]
  pull_request:
    branches: [ "main", "developer" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configuração do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Versão recomendada para Next.js
          cache: "npm"       # Habilita o cache para dependências npm

      # 3. Instalar dependências
      - name: Install dependencies
        run: npm install

      # 6. Build do projeto
      - name: Build project
        # env:
        #   NEXT_PUBLIC_API_URL: "https://api.example.com" # Adicione suas variáveis de ambiente aqui
        run: npm run build


